### ISSUE TITLE
Cannot find git on windows

### ISSUE THREAD

**Issue by doggy-dev** [javaee/copyright-maven-plugin#4]
I'm trying to run the plugin on a windows machine and I get an IOException that the git executable cannot be found. I have git installed and the git.exe executable is in my Paht variable.

**Comment by bshannon** [comment]
Sorry, I never use Windows.  The plugin just uses the JDK's ProcessBuilder class
to run the "git" command.  Can you run "git" in a command window?  How are you
running the copyright plugin?

**Comment by doggy-dev** [comment]
Yes, I can run git in the command window from anywhere - it is my PATH sys var. I run the plugin in eclipse as maven build and set the goal to glassfish-copyright:check.

**Comment by bshannon** [comment]
Try running maven from the command line and see if that makes a difference.

**Comment by doggy-dev** [comment]
Yes it worked from command line. I'll search for the reason from here on, thanks.

**Comment by bshannon** [comment]
I believe you have to set the PATH somewhere very early in Windows in order for it to effect any GUI applications you start.
